spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_tracker_hibernate
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show-sql: true

fx:
  baseUrl: https://free.currencyconverterapi.com/api/v6/convert?q=

## App Properties
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000